# Generated by Django 4.2.4 on 2023-09-04 16:33

import booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='class',
            name='date',
            field=models.DateField(default=booking.models.get_today_date),
        ),
        migrations.AddField(
            model_name='class',
            name='time',
            field=models.TimeField(default=booking.models.get_current_time),
        ),
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.teacher'),
        ),
    ]
